title: ¡Hola!
description: <body><p>My site is under unstruction🚀</p>
<p>I may update some notes around Machine Learning or so <del>If I got time, most probably won&#39;t.</del></p>
<p>So since you&#39;ve found my site, how about explore it a little bit more🤩</p>
<p>&nbsp;</p>

  <h3>indexes</h3>
  <a href="#Optics">Optics</a><br>
  <a href="#TM">Theoratical Mechanism</a><br>
  <a href="#ED">Electrodynamics</a></body>
theme: jekyll-theme-minimal
