title: ¡Hola!
description: this is my personal site!<br>
<h3>indexes</h3><br>
<a href="#Optics">Optics</a>
<a href="#TM>Theoratical Mechanism</a>
<a href="#ED">Electrodynamics</a>
theme: jekyll-theme-minimal
