title: ¡Hola!
description: <body> this is my personal site!<br>
s1: <h3>indexes</h3><br>
s2: <a href="#Optics">Optics</a><br>
s3: <a href="#TM>TheoraticalMechanism</a><br>
s4: <a href="#ED">Electrodynamics</a></body>
theme: jekyll-theme-minimal
